# 将静态内容部署到 GitHub 页面的简单工作流程
name:将静态内容部署到页面

on:
    # 在针对默认分支的推送上运行
    push:
        branches: ["master"]

    # 允许您从“操作”选项卡手动运行此工作流
    workflow_dispatch:

# 设置GITHUB_TOKEN的权限以允许部署到 GitHub 页面
permissions:
    contents: read
    pages: write
    id-token: write

# 仅允许一个并发部署，跳过在正在进行的运行和最新排队的运行之间排队的运行。
# 但是，请勿取消正在进行的运行，因为我们希望允许这些生产部署完成。
concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    # 单个部署作业，因为我们只是在部署
    deploy:
        environment:
            name: GitHub 页面
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: 检出
              uses: actions/checkout@v3
            - name: 设置页面
              uses: actions/configure-pages@v3
            - name: 上传页面工件
              uses: actions/upload-pages-artifact@v1
              with:
                  # Upload entire repository
                  path: '.'
            - name: 部署到 GitHub 页面
              id: deployment
              uses: actions/deploy-pages@v2
