name: 部署到 GitHub 页面

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        defaults:
            run:
                working-directory: '.'
        steps:
            - name: 检出
              uses: actions/checkout@v3

            - name: 设置 Node
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: 获取 Yarn 缓存
              id: yarn-cache
              run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> "${GITHUB_OUTPUT}"

            - name: 缓存依赖项
              uses: actions/cache@v3
              with:
                  path: ${{ steps.yarn-cache.outputs.YARN_CACHE_DIR }}
                  key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-website-

            - name: 安装依赖包
              run: yarn install --frozen-lockfile

            - name: 构建
              run: yarn build

            - name: 部署
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/master' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  # 构建输出以发布到“gh-pages”分支：
                  publish_dir: ./build
                  # 以下行将提交作者身份分配给官方 GH 操作机器人，以便部署到“gh-pages”分支：
                  # https://github.com/actions/checkout/issues/13#issuecomment-724415212
                  # 如果未指定这两个字段，则默认使用 GH 操作机器人。
                  # 您可以将它们换成您自己的用户凭据。
